In [1]:
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import sent_tokenize # tokenizes sentences
import re
from nltk.stem import PorterStemmer
from nltk.tag import pos_tag
from nltk.corpus import stopwords
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
#Machine Learning
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import metrics # for confusion matrix, accuracy score etc
from sklearn.model_selection import train_test_split

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('words')


[nltk_data] Downloading package stopwords to /home/gilo/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/gilo/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /home/gilo/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package words to /home/gilo/nltk_data...
[nltk_data]   Package words is already up-to-date!


True

In [3]:

df =data_preprocessing()



Started dataset loading: 
Datasets ready to use!
Total Length of DataFrame is 692

 Study the cat


TweetText
cat                
buglary           8
homicide        278
rape             74
robbery         332

In [26]:
df.head




<bound method NDFrame.head of                                              TweetText       cat
2    #Vancouver police homicide squad investigates ...  homicide
4    #RCMP dive team in waters off Neck Point Park ...  homicide
9    #Homicide. Over a small amount of marijuana an...  homicide
13   #MN man who did time for pipe #bombs now wante...  homicide
15   ℕ𝔼𝕎⦙  President of Mongols bikie cha...  homicide
..                                                 ...       ...
225  Follow our\n TRAIN OF CHANGE\nSign our 3 urgen...      rape
226  #Petition updates.\nFigures still slowing down...      rape
227  The situation in the #DRC & #SouthSudan calls ...      rape
228  The government’s #rape review: an apology, b...      rape
230  Let’s all stick to the facts.\nStuart Lubboc...      rape

[692 rows x 2 columns]>

In [6]:
cleaner =clean_tweets(df)

example before cleaning at position 4
ℕ𝔼𝕎⦙  President of Mongols bikie chapter arrested over alleged murder of Finks bikie Shane Bowden #Crime #Homicide 
@abcnews
 VIA 
@headlines24_7
example after cleaning at position 4
President Mongols bikie chapter arrested alleged murder Finks bikie Shane Bowden Crime Homicide VIA


/usr/lib/python3/dist-packages/ipykernel_launcher.py:27: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access


In [38]:
np.random.choice(cleaner.TweetText)

'One Dead Double Shooting Citgo Gas Station Wyoming Ave MI Headlines via detroit wyomingave citgo homicide'

In [9]:
forest, vectorizer, feature_names, importances = classify_forest(cleaner.TweetText,cleaner.cat)

Creating the bag of words model!

Training the random forest classifier!

The training accuracy is:  0.9981916817359855 
 The validation accuracy is:  0.9784172661870504
confusion matrix
[[ 3  0  0  0]
 [ 0 51  0  2]
 [ 0  0 16  0]
 [ 0  1  0 66]]
check classes on which we trained
['buglary' 'homicide' 'rape' 'robbery']
[8.88808665e-07 1.17353457e-05 0.00000000e+00 ... 0.00000000e+00
 9.01295884e-04 1.15845111e-04]
Feature ranking:
['homicide', 'robbery', 'rape', 'death', 'may', 'truecrime', 'de', 'buglary', 'sexualassault', 'murder', 'montreal', 'violence', 'investigation', 'rapeculture', 'delhi', 'atm', 'india', 'metoo', 'mumbai', 'pour', 'robbed', 'minor', 'another', 'armed', 'replying', 'shooting', 'sirrapedr', 'gib', 'read', 'girl', 'femicide', 'unsolved', 'gohabsgo', 'un', 'hospital', 'homme', 'sbi', 'killed', 'sexual', 'women', 'le', 'crime', 'others', 'roh', 'tvgujaraticom', 'today', 'cctv', 'jun', 'fatal', 'rajasthan']


In [12]:
print(importances)

[1.64390285e-07 0.00000000e+00 1.61510539e-04 ... 0.00000000e+00
 9.37577203e-04 1.31666269e-04]


In [55]:
cList = {
  "ain't": "am not",
  "aren't": "are not",
  "can't": "cannot",
  "can't've": "cannot have",
  "'cause": "because",
  "could've": "could have",
  "couldn't": "could not",
  "couldn't've": "could not have",
  "didn't": "did not",
  "doesn't": "does not",
  "don't": "do not",
  "hadn't": "had not",
  "hadn't've": "had not have",
  "hasn't": "has not",
  "haven't": "have not",
  "he'd": "he would",
  "he'd've": "he would have",
  "he'll": "he will",
  "he'll've": "he will have",
  "he's": "he is",
  "how'd": "how did",
  "how'd'y": "how do you",
  "how'll": "how will",
  "how's": "how is",
  "I'd": "I would",
  "I'd've": "I would have",
  "I'll": "I will",
  "I'll've": "I will have",
  "i'm": "i am",
  "I've": "I have",
  "isn't": "is not",
  "it'd": "it had",
  "it'd've": "it would have",
  "it'll": "it will",
  "it'll've": "it will have",
  "it's": "it is",
  "let's": "let us",
  "ma'am": "madam",
  "mayn't": "may not",
  "might've": "might have",
  "mightn't": "might not",
  "mightn't've": "might not have",
  "must've": "must have",
  "mustn't": "must not",
  "mustn't've": "must not have",
  "needn't": "need not",
  "needn't've": "need not have",
  "o'clock": "of the clock",
  "oughtn't": "ought not",
  "oughtn't've": "ought not have",
  "shan't": "shall not",
  "sha'n't": "shall not",
  "shan't've": "shall not have",
  "she'd": "she would",
  "she'd've": "she would have",
  "she'll": "she will",
  "she'll've": "she will have",
  "she's": "she is",
  "should've": "should have",
  "shouldn't": "should not",
  "shouldn't've": "should not have",
  "so've": "so have",
  "so's": "so is",
  "that'd": "that would",
  "that'd've": "that would have",
  "that's": "that is",
  "there'd": "there had",
  "there'd've": "there would have",
  "there's": "there is",
  "they'd": "they would",
  "they'd've": "they would have",
  "they'll": "they will",
  "they'll've": "they will have",
  "they're": "they are",
  "they've": "they have",
  "to've": "to have",
  "wasn't": "was not",
  "we'd": "we had",
  "we'd've": "we would have",
  "we'll": "we will",
  "we'll've": "we will have",
  "we're": "we are",
  "we've": "we have",
  "weren't": "were not",
  "what'll": "what will",
  "what'll've": "what will have",
  "what're": "what are",
  "what's": "what is",
  "what've": "what have",
  "when's": "when is",
  "when've": "when have",
  "where'd": "where did",
  "where's": "where is",
  "where've": "where have",
  "who'll": "who will",
  "who'll've": "who will have",
  "who's": "who is",
  "who've": "who have",
  "why's": "why is",
  "why've": "why have",
  "will've": "will have",
  "won't": "will not",
  "wont": "will not",
  "won't've": "will not have",
  "would've": "would have",
  "wouldn't": "would not",
  "wouldn't've": "would not have",
  "y'all": "you all",
  "y'alls": "you alls",
  "y'all'd": "you all would",
  "y'all'd've": "you all would have",
  "y'all're": "you all are",
  "y'all've": "you all have",
  "you'd": "you had",
  "you'd've": "you would have",
  "you'll": "you will",
  "you'll've": "you will have",
  "you're": "you are",
  "youre": "you are",
  "you've": "you have",
  "youve": "you have",
  "yall": "you all",
  "ya'll": "you all"
}

c_re = re.compile('(%s)' % '|'.join(cList.keys()))

def expandContractions(text, c_re=c_re):
    def replace(match):
        return cList[match.group(0)]
    text = c_re.sub(replace, text.lower())
    return text



tweets = list(df.TweetText)

for i in tweets:
    
    df['text'] = expandContractions(i)
    
 

In [10]:
 train,test = train_test_split(cleaner.TweetText, random_state=0, test_size=.2)


In [11]:
len(train)

553

In [2]:
def data_preprocessing():
    

    print('Started dataset loading: ')
    
    
#     fl ="metoo_tweets_dec2017.csv"
    homicide = pd.read_csv('homicide_data.csv',skip_blank_lines=True, encoding = "ISO-8859-1")
    homicide['cat'] = 'homicide'

    rape = pd.read_csv('twitter_data.csv',skip_blank_lines=True, encoding = "ISO-8859-1")
    rape['cat'] = 'rape'

    robbery = pd.read_csv('robbery_data.csv',skip_blank_lines=True, encoding = "ISO-8859-1")
    robbery['cat'] = 'robbery'

    buglary = pd.read_csv('barglary_data.csv',skip_blank_lines=True, encoding = "ISO-8859-1")
    buglary['cat'] = 'buglary'

    
    #make into one dataframe
    
    df = pd.concat([homicide,robbery,buglary,rape])


    #drop unneccessary columns
    df = df.drop(['User','Handle',
                  'ReplyCount','RetweetCount','PostDate'], axis=1)
    
#     #drop nan values
    df = df.dropna()
    df = df[['TweetText','cat']]
    
    print('Datasets ready to use!')
    
    print('Total Length of DataFrame is', len(df))
    
    print('\n Study the cat')
    display(df.groupby(['cat']).count())
    
    
    return df

In [5]:
def  clean_tweets(df,hashtag_just_sign=True, remove_stopwords=True,test_position=4,remove_digits=True):
    print('example before cleaning at position', test_position)
    print(df.iloc[test_position].TweetText)
    
    #IN ANY CASE 
    #non alpabetical/ numerical
    df = df.replace(to_replace =r'&amp;', value = '', regex = True)
    df = df.replace(to_replace =r'&gt;', value = '', regex = True)
    #hyperlinks
    df = df.replace(to_replace =r'http\S+', value = '', regex = True)
    #usernames
    df = df.replace(to_replace =r'@\S+', value = '', regex = True) 
    #remove retweet
    df = df.replace(to_replace ='RT :', value = '', regex = True) 
    df = df.replace(to_replace ='RT ', value = '', regex = True)
    
    #HASHTAG OPTIONAL REMOVE
    if(hashtag_just_sign == True):
        df = df.replace(to_replace ='#', value = '', regex = True) 
    else:
        df = df.replace(to_replace =r'#\S+', value = '', regex = True)
        
    #IN ANY CASE
    #remove punctation
    df = df.replace(to_replace ='[",:!?\\-]', value = ' ', regex = True)
    #4. Tokenize into words (all lower case)
    df.text = df.TweetText.str.lower()
    
    #make sure no weird letters left
    #remove digits
    df = df.replace(to_replace ='[\d+]', value = '', regex = True)
    #special characters
    pattern = r'[^a-zA-z0-9\s]' if not remove_digits else r'[^a-zA-z\s]'
    
    df = df.replace(to_replace =pattern, value = '', regex = True)
    
    
    
    #u = df.select_dtypes(object)
    df['TweetText'] = df['TweetText'].apply(lambda x: x.encode('ascii', 'ignore').decode('ascii'))
    
    if(remove_stopwords == True):
        df.TweetText = df.TweetText.str.split() 
        eng_stopwords = set(stopwords.words("english"))
        df['TweetText'] = df['TweetText'].apply(lambda x: [item for item in x if item not in eng_stopwords])
        #join the list items back to one string
        df['TweetText'] = df['TweetText'].apply(lambda x: ' '.join(x))

    
    
    print('example after cleaning at position', test_position)
    print(df.iloc[test_position].TweetText)
    
    return df
    

### classify datasets


 

In [8]:
def classify_forest(data, y):

    print("Creating the bag of words model!\n")
    # CountVectorizer" is scikit-learn's bag of words tool, here we show more keywords 
    vectorizer = CountVectorizer(analyzer = "word",   \
                                 tokenizer = None,    \
                                 preprocessor = None, \
                                 stop_words = None,   \
                                 max_features = 2000) 
    
    X_train, X_test, y_train, y_test = train_test_split(\
    data, y, random_state=0, test_size=.2)

    # Then we use fit_transform() to fit the model / learn the vocabulary,
    # then transform the data into feature vectors.
    # The input should be a list of strings. .toarraty() converts to a numpy array
    
    train_bag = vectorizer.fit_transform(X_train).toarray()
    test_bag = vectorizer.transform(X_test).toarray()

    # You can extract the vocabulary created by CountVectorizer
    # by running print(vectorizer.get_feature_names())


    print("Training the random forest classifier!\n")
    # Initialize a Random Forest classifier with 75 trees
    forest = RandomForestClassifier(n_estimators = 50) 

    # Fit the forest to the training set, using the bag of words as 
    # features and the sentiment labels as the target variable
    forest = forest.fit(train_bag, y_train)

    train_predictions = forest.predict(train_bag)
    test_predictions = forest.predict(test_bag)
    
    train_acc = metrics.accuracy_score(y_train, train_predictions)
    valid_acc = metrics.accuracy_score(y_test, test_predictions)
    print("The training accuracy is: ", train_acc, "\n", "The validation accuracy is: ", valid_acc)
    
    print('confusion matrix')
    print(metrics.confusion_matrix(y_test,test_predictions))
    
    print('check classes on which we trained')
    print(forest.classes_)
    
    importances = forest.feature_importances_
    # returns relative importance of all features.
    # they are in the order of the columns
    print(importances)
    len(importances)

    feature_names = vectorizer.get_feature_names()
    # sort importance scores
    
    indices = np.argsort(importances)[::-1]
    # Print the feature ranking
    print("Feature ranking:")
    top_50 = indices[:50]
    top50_features = [vectorizer.get_feature_names()[ind] for ind in top_50]
    print(top50_features)
    
    return(forest, vectorizer, feature_names, importances)
    
    


In [12]:
cls =forest.predict(vectorizer.transform(['help am being chased, he has a panga']).astype('float'))[0]
print(cls)

robbery


In [13]:
import joblib
import tqdm
from nltk.corpus import words

joblib.dump(forest, '../urgent/service_NLP/models/ml_model.jb')
joblib.dump(vectorizer, '../urgent/service_NLP/models/vectorizer.jb')

dtf = pd.DataFrame(np.vstack((feature_names, importances))).transpose()
dtf.columns = ['feature', 'importance']
dtf.set_index('feature', inplace=True)
msk = np.asarray([np.any([c.isdigit() for c in w]) for w in dtf.index])
dtf = dtf[~msk]
exi = np.asarray([w in set(words.words()) for w in tqdm.tqdm(dtf.index)])
dtf[exi].to_parquet('../urgent/service_NLP/models/vocabulary.pq')

100%|██████████| 2000/2000 [04:29<00:00,  7.42it/s]
